const GALLERY_DATA = {
  villas: [
    "images/serenity-villas/aerial-view.jpg",
    "images/serenity-villas/bathroom.jpg",
    "images/serenity-villas/exterior-view.jpg",
    "images/serenity-villas/progress-photo.jpg",
    "images/serenity-villas/R1_Bath_ (1).jpg",
    "images/serenity-villas/R1_Bath_ (2).jpg",
    "images/serenity-villas/R1_Bath_ (3).jpg",
    "images/serenity-villas/R1_Bath_ (4).jpg",
    "images/serenity-villas/R1_BR_ (1).jpg",
    "images/serenity-villas/R1_BR_ (2).jpg",
    "images/serenity-villas/R1_BR_ (3).jpg",
    "images/serenity-villas/R1_LR_K_ (1).jpg",
    "images/serenity-villas/R1_LR_K_ (2).jpg",
    "images/serenity-villas/R1_LR_K_ (3).jpg",
    "images/serenity-villas/R1_LR_K_ (4).jpg",
    "images/serenity-villas/R1_LR_K_ (5).jpg",
    "images/serenity-villas/R1_LR_K_ (6).jpg",
    "images/serenity-villas/R23_Bath_.jpg",
    "images/serenity-villas/R23_BR_.jpg",
    "images/serenity-villas/R23_LR_K_ (1).jpg",
    "images/serenity-villas/R23_LR_K_ (2).jpg",
    "images/serenity-villas/R23_LR_K_ (3).jpg",
    "images/serenity-villas/villa-b1.jpg",
    "images/serenity-villas/waterfall.jpg"
  ],
  estates: [
    "images/serenity-estates/pool-villa-a1.jpg",
    "images/serenity-estates/Static.0000.jpg",
    "images/serenity-estates/Static.0001.jpg",
    "images/serenity-estates/Static.0002.jpg",
    "images/serenity-estates/Static.0003.jpg",
    "images/serenity-estates/Static.0004.jpg",
    "images/serenity-estates/Static.0005.jpg",
    "images/serenity-estates/Static.0006.jpg",
    "images/serenity-estates/Static.0007.jpg",
    "images/serenity-estates/Static.0008.jpg",
    "images/serenity-estates/Static.0009.jpg",
    "images/serenity-estates/Static.0010.jpg",
    "images/serenity-estates/Static.0011.jpg",
    "images/serenity-estates/Static.0012.jpg",
    "images/serenity-estates/Static.0013.jpg",
    "images/serenity-estates/Static.0014.jpg",
    "images/serenity-estates/Static.0015.jpg",
    "images/serenity-estates/Static.0016.jpg",
    "images/serenity-estates/Static.0017.jpg",
    "images/serenity-estates/Static.0018.jpg",
    "images/serenity-estates/villa-a1.jpg",
    "images/serenity-estates/villa-a2.jpg",
    "images/serenity-estates/villa-b1.jpg",
    "images/serenity-estates/villa-b2.jpg"
  ],
  village: [
    "images/serenity-village/1BR S Village_Exter.jpeg",
    "images/serenity-village/1BR S Village_Living room.jpg",
    "images/serenity-village/1BR S Village_Living room_2 .jpg",
    "images/serenity-village/1BR S Village_Living room_3.jpg",
    "images/serenity-village/1BR.0000.jpg",
    "images/serenity-village/2BR.0000.jpg",
    "images/serenity-village/4House_Max.0001.jpg",
    "images/serenity-village/6House_Max.0001.jpg",
    "images/serenity-village/Front_2BR.0001.jpg",
    "images/serenity-village/House_night.0000.jpg",
    "images/serenity-village/Interior_sun.0001.jpg",
    "images/serenity-village/Night.0000.jpg",
    "images/serenity-village/Night.0001.jpg",
    "images/serenity-village/Night_green_Max.0000.jpg",
    "images/serenity-village/Night_Max.0000.jpg",
    "images/serenity-village/Pool_Max.0000.jpg",
    "images/serenity-village/Pool_Max2.0001.jpg",
    "images/serenity-village/Restoran.0000.jpg",
    "images/serenity-village/S Village_Bathroom 2.jpeg",
    "images/serenity-village/S Village_Bathroom.jpeg",
    "images/serenity-village/S Village_Bedroom .jpeg",
    "images/serenity-village/S Village_Bedroom_2.jpeg",
    "images/serenity-village/S Village_Bedroom_3.jpeg",
    "images/serenity-village/SunRise.0001.jpg",
    "images/serenity-village/SV 3.0.jpeg",
    "images/serenity-village/SVg_MasterPlan.0000.jpg"
  ],
};