const GALLERY_DATA = {
  villas: [
    "images/serenity-villas/aerial-view.webp",
    "images/serenity-villas/bathroom.webp",
    "images/serenity-villas/complex-overview.webp",
    "images/serenity-villas/exterior-view.webp",
    "images/serenity-villas/progress-photo.webp",
    "images/serenity-villas/R1_Bath_ (1).webp",
    "images/serenity-villas/R1_Bath_ (2).webp",
    "images/serenity-villas/R1_Bath_ (3).webp",
    "images/serenity-villas/R1_Bath_ (4).webp",
    "images/serenity-villas/R1_BR_ (1).webp",
    "images/serenity-villas/R1_BR_ (2).webp",
    "images/serenity-villas/R1_BR_ (3).webp",
    "images/serenity-villas/R1_LR_K_ (1).webp",
    "images/serenity-villas/R1_LR_K_ (2).webp",
    "images/serenity-villas/R1_LR_K_ (3).webp",
    "images/serenity-villas/R1_LR_K_ (4).webp",
    "images/serenity-villas/R1_LR_K_ (5).webp",
    "images/serenity-villas/R1_LR_K_ (6).webp",
    "images/serenity-villas/R23_Bath_.webp",
    "images/serenity-villas/R23_BR_.webp",
    "images/serenity-villas/R23_LR_K_ (1).webp",
    "images/serenity-villas/R23_LR_K_ (2).webp",
    "images/serenity-villas/R23_LR_K_ (3).webp",
    "images/serenity-villas/villa-b1.webp",
    "images/serenity-villas/waterfall.webp"
  ],
  estates: [
    "images/serenity-estates/pool-villa-a1.webp",
    "images/serenity-estates/Static.0000.webp",
    "images/serenity-estates/Static.0001.webp",
    "images/serenity-estates/Static.0002.webp",
    "images/serenity-estates/Static.0003.webp",
    "images/serenity-estates/Static.0004.webp",
    "images/serenity-estates/Static.0005.webp",
    "images/serenity-estates/Static.0006.webp",
    "images/serenity-estates/Static.0007.webp",
    "images/serenity-estates/Static.0008.webp",
    "images/serenity-estates/Static.0009.webp",
    "images/serenity-estates/Static.0010.webp",
    "images/serenity-estates/Static.0011.webp",
    "images/serenity-estates/Static.0012.webp",
    "images/serenity-estates/Static.0013.webp",
    "images/serenity-estates/Static.0014.webp",
    "images/serenity-estates/Static.0015.webp",
    "images/serenity-estates/Static.0016.webp",
    "images/serenity-estates/Static.0017.webp",
    "images/serenity-estates/Static.0018.webp",
    "images/serenity-estates/villa-a1.webp",
    "images/serenity-estates/villa-a2.webp",
    "images/serenity-estates/villa-b1.webp",
    "images/serenity-estates/villa-b2.webp"
  ],
  village: [
    "images/serenity-village/1BR S Village_Exter.webp",
    "images/serenity-village/1BR S Village_Living room.webp",
    "images/serenity-village/1BR S Village_Living room_2 .webp",
    "images/serenity-village/1BR S Village_Living room_3.webp",
    "images/serenity-village/1BR.0000.webp",
    "images/serenity-village/2BR.0000.webp",
    "images/serenity-village/4House_Max.0001.webp",
    "images/serenity-village/6House_Max.0001.webp",
    "images/serenity-village/Front_2BR.0001.webp",
    "images/serenity-village/House_night.0000.webp",
    "images/serenity-village/Interior_sun.0001.webp",
    "images/serenity-village/Night.0000.webp",
    "images/serenity-village/Night.0001.webp",
    "images/serenity-village/Night_green_Max.0000.webp",
    "images/serenity-village/Night_Max.0000.webp",
    "images/serenity-village/Pool_Max.0000.webp",
    "images/serenity-village/Pool_Max2.0001.webp",
    "images/serenity-village/Restoran.0000.webp",
    "images/serenity-village/S Village_Bathroom 2.webp",
    "images/serenity-village/S Village_Bathroom.webp",
    "images/serenity-village/S Village_Bedroom .webp",
    "images/serenity-village/S Village_Bedroom_2.webp",
    "images/serenity-village/S Village_Bedroom_3.webp",
    "images/serenity-village/SunRise.0001.webp",
    "images/serenity-village/SV 3.0.webp",
    "images/serenity-village/SVg_MasterPlan.0000.webp"
  ],
};