/**
 * Build script · Supabase site_content → static .js files
 *
 * Запускается на каждом Vercel build:
 *   1. Подключается к Supabase service_role-ключом
 *   2. SELECT всех 5 row из public.site_content
 *   3. Генерит data/site-data.js, data/projects-data.js, data/faq-data.js,
 *      data/testimonials-data.js, gallery-data.js — те же файлы что были
 *      раньше, с теми же именами глобальных констант (SITE_DATA, ...).
 *
 * Локальный запуск (для тестов):
 *   SUPABASE_URL=https://xxx.supabase.co \
 *   SUPABASE_SERVICE_ROLE_KEY=sb_secret_xxx \
 *   node scripts/build-data.mjs
 *
 * На Vercel: env vars берутся из Project Settings → Environment Variables.
 *
 * Безопасность: service_role-ключ имеет полный доступ к БД и обходит RLS.
 * Доступен ТОЛЬКО на сервере (Vercel build runner) — никогда не уходит в браузер.
 */

import { createClient } from '@supabase/supabase-js';
import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const ROOT = resolve(dirname(__filename), '..');

// ─── env ───
const SUPABASE_URL = process.env.SUPABASE_URL;
const SERVICE_ROLE = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_URL || !SERVICE_ROLE) {
  console.error('❌ SUPABASE_URL и SUPABASE_SERVICE_ROLE_KEY обязательны.');
  console.error('   На Vercel: Project Settings → Environment Variables.');
  console.error('   Локально: запускай с env-переменными или через .env.local.');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SERVICE_ROLE, {
  auth: { autoRefreshToken: false, persistSession: false },
});

// ─── маппинг key → файл + имя глобальной константы ───
const TARGETS = {
  site:         { file: 'data/site-data.js',         varName: 'SITE_DATA' },
  projects:     { file: 'data/projects-data.js',     varName: 'PROJECTS_DATA' },
  faq:          { file: 'data/faq-data.js',          varName: 'FAQ_DATA' },
  testimonials: { file: 'data/testimonials-data.js', varName: 'TESTIMONIALS_DATA' },
  gallery:      { file: 'gallery-data.js',           varName: 'GALLERY_DATA' },
};

// ─── helpers ───
function ensureDir(filePath) {
  const dir = dirname(filePath);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
}

function isEmptyData(data) {
  if (data === null || data === undefined) return true;
  if (Array.isArray(data)) return data.length === 0;
  if (typeof data === 'object') return Object.keys(data).length === 0;
  return false;
}

// ─── main ───
async function main() {
  console.log(`🔨 Build start · Supabase: ${SUPABASE_URL}`);

  const { data: rows, error } = await supabase
    .from('site_content')
    .select('key, data, updated_at');

  if (error) {
    console.error('❌ SELECT site_content failed:', error.message);
    process.exit(1);
  }

  if (!rows || rows.length === 0) {
    console.error('❌ site_content пустая. Запусти миграцию данных:');
    console.error('   npm run migrate-content');
    process.exit(1);
  }

  // Защита: если все 5 row пустые/дефолтные — это первый деплой до миграции.
  // Падаем явно, чтобы не выкатить пустой сайт.
  const allEmpty = rows.every(r => isEmptyData(r.data));
  if (allEmpty) {
    console.error('❌ Все site_content row пустые. Нужно запустить миграцию контента:');
    console.error('   npm run migrate-content');
    process.exit(1);
  }

  let written = 0;
  let skipped = 0;

  for (const target of Object.keys(TARGETS)) {
    const row = rows.find(r => r.key === target);
    if (!row) {
      console.warn(`⚠️  site_content row для key="${target}" не найдена — пропускаем.`);
      skipped++;
      continue;
    }

    if (isEmptyData(row.data)) {
      console.warn(`⚠️  site_content[${target}] пустая — пропускаем (старый файл сохранится).`);
      skipped++;
      continue;
    }

    const { file, varName } = TARGETS[target];
    const fullPath = resolve(ROOT, file);
    ensureDir(fullPath);

    const json = JSON.stringify(row.data, null, 2);
    const content = `/* eslint-disable */\n/* AUTO-GENERATED by scripts/build-data.mjs · DO NOT EDIT MANUALLY */\n/* Source: Supabase site_content[${target}] · updated ${row.updated_at} */\nconst ${varName} = ${json};\n`;

    writeFileSync(fullPath, content, 'utf8');
    console.log(`✅ ${file} (${(content.length / 1024).toFixed(1)} KB)`);
    written++;
  }

  console.log(`\n🎉 Build done · ${written} files written, ${skipped} skipped.`);
}

main().catch(err => {
  console.error('❌ Build failed:', err);
  process.exit(1);
});
